# This will create a docker image named gcr.io/[PROJECT_ID]/proxy:[TAG] locally.
# The PROJECT_ID is the current project name that gcloud uses.
#
# To manually trigger a build on GCB, run:
# gcloud builds submit --config cloudbuild-proxy.yaml --substitutions TAG_NAME=[TAG] ..
#
# To trigger a build automatically, follow the instructions below and add a trigger:
# https://cloud.google.com/cloud-build/docs/running-builds/automate-builds
steps:
# Download saved Gradle distribution from GCS and install it.
- name: 'gcr.io/${PROJECT_ID}/builder:latest'
  entrypoint: ./release/install_gradle.sh
# Build the proxy docker image.
- name: 'gcr.io/${PROJECT_ID}/builder:latest'
  args:
  - ./gradlew
  - :proxy:test
  - :proxy:buildProxyImage
  - -PmavenUrl=gcs://domain-registry-maven-repository/maven
  - -PpluginsUrl=gcs://domain-registry-maven-repository/plugins
# Tag the image for staging repository.
- name: 'gcr.io/${PROJECT_ID}/builder:latest'
  entrypoint: /bin/bash
  args:
  - -c
  - |
    set -e
    docker tag proxy us-docker.pkg.dev/${PROJECT_ID}/staging/proxy:${TAG_NAME}
    docker tag proxy us-docker.pkg.dev/${PROJECT_ID}/staging/proxy:latest
  dir: 'proxy'
# Images to upload to staging repository for build provenance generation.
images:
  - 'us-docker.pkg.dev/${PROJECT_ID}/staging/proxy:${TAG_NAME}'
  - 'us-docker.pkg.dev/${PROJECT_ID}/staging/proxy:latest'
# Config files to upload to GCS.
artifacts:
  objects:
    location: 'gs://${PROJECT_ID}-deploy/${TAG_NAME}'
    # This cannot be regexs because of how Spinnaker constructs artifact paths.
    paths:
    - 'proxy/kubernetes/proxy-*.yaml'
timeout: 3600s
options:
  machineType: 'E2_HIGHCPU_32'
